name: CI Noc Documentation
on: [push]

jobs:
  noc:
    name: Generate the Noc documentation with nocdoc tool
    runs-on: ubuntu-latest

    steps:
    - uses: haskell/actions/setup@v1.2

    # Build Noc
    - run: wget https://github.com/mortim/noc/releases/download/v0.1.0.0/noc-v0.1.0.0-patch.zip
      name: Download the Noc v0.1.0.0 release version
    - run: unzip ./noc-v0.1.0.0-patch.zip
    - run: make install
      working-directory: noc-v0.1.0.0-patch
      name: Building/Installing the Noc interpreter
    - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

    # Build the Noc documentation
    - run: wget https://raw.githubusercontent.com/mortim/nocdoc/master/nocdoc.noc
      working-directory: noc-v0.1.0.0-patch
    - run: make build_doc
      name: Generate the documentation with nocdoc tool
      working-directory: noc-v0.1.0.0-patch
    
    # Deploy the Noc documentation
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./noc-v0.1.0.0-patch/noc_documentation
